summary: Listar productos activos con stock
description: |
  Devuelve la lista de productos que están activos y cuyo stock es mayor a cero,
  incluyendo categoría y subcategoría.
tags:
  - Catálogo
responses:
  200:
    description: Productos obtenidos con éxito
    schema:
      type: array
      items:
        type: object
        properties:
          id_producto:
            type: integer
            example: 123
          categoria:
            type: string
            example: "Electrónica"
          subcategoria:
            type: string
            example: "Smartphones"
          nombre:
            type: string
            example: "Teléfono Modelo X"
          precio:
            type: number
            example: 499.99
          imagen:
            type: string
            example: "https://.../imagen.jpg"
          stock:
            type: integer
            example: 25
  500:
    description: Error interno al obtener productos
    schema:
      type: object
      properties:
        error:
          type: string
          example: "Error interno al obtener productos"
